# Generated by Django 2.0.7 on 2018-08-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationBody',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('_type', models.CharField(max_length=200)),
                ('_content', models.TextField()),
            ],
        ),
    ]
